edit: main.o add.o minus.o product.o deduct.o
	gcc -o edit main.o add.o minus.o product.o deduct.o

main.o: main.c head1.h
	gcc -c main.c 

add.o: add.c head1.h
	gcc -c add.c

minus.o: minus.c head1.h
	gcc -c minus.c

product.o: product.c head1.h
	gcc -c product.c

deduct.o: deduct.c head1.h
	gcc -c deduct.c
